version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers: [ console ]
    propagate: False
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: False
  reports_api:
    level: INFO
    handlers: [console]
    propagate: False
root:
  level: INFO
  handlers: [console]
